name: Download Weather Data and Push to Repository

# Trigger the workflow manually or on a schedule
on:
  schedule:
    # Runs at 10:00 AM every day
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up the environment for running weather.sh
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
        run: |
          python -m pip install
          --upgrade pip
          pip install -r requirements.txt

    # Step 3: Run the weather.sh script to download the data
    - name: Download Weather Data
      run: 
        weather.sh

    # Step 4: Add, commit, and push the new data file
    - name: Commit and Push Data
      run: |
        git add .
        git commit -m "Add new weather data"
        git push origin main 
              env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
