name: Download Weather Data and Push to Repository

# Trigger the workflow manually or on a schedule
on:
  schedule:
    # Runs at 10:00 AM every day
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    # Step 2: Set up the environment for running weather.sh
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: 
        pip install -r requirements.txt

    # Step 4: Run the weather.sh script to download the data
    - name: Download Weather Data
      run: 
        ./weather.sh

    # Step 5: Add, commit, and push the new data file
    - name: Commit and Push Data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add new weather data"
        git push origin main
